Server:
  error:
    include-message: always
    include-binding-errors: always
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/schooldb
    username: root
    password: deenn1019.
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format-sql: true
      show-sql: true